### ISSUE TITLE
💡 [FEAT]: - Add frogs legs

### ISSUE THREAD

**Issue by kg7pnh** [bayhasoft/adventurers-cookbook#23]
### Summary

Minecraft has frogs in the game. The idea of having frogs legs available as something that can be used as a food source sounds like a good idea. 

### Basic Example

We should add the following:

- frogs legs (0-2) to the loot table for frogs,
- a model for the raw frogs legs when the dropped,
- a texture for the raw frogs legs model,
- a recipe for cooking raw frogs legs into cooked frogs legs,
- a model for the cooked frogs legs,
- a texture for the cooked frogs legs model,
- possible option(s) for the butcher and / or fisherman to buy raw frogs legs
- possible option(s) for the butcher and / or fisherman to sell cooked frogs legs
- possible uses in brewing?

### Drawbacks

The question of why. What would be the real reason for adding them? Would it be just for the purpose of making the frog "useful"?

**Comment by KJ7GDS** [comment]
what would be there use in brewing?
